### ISSUE TITLE
Webpack module parse failed.

### ISSUE THREAD

**Issue by nirrek** [dubert/react-kronos#13]
```
ERROR in ./~/react-kronos/~/color/~/color-string/~/color-name/index.json
Module parse failed: /Users/nirrek/Projects/project/node_modules/react-kronos/node_modules/color/node_modules/color-string/node_modules/color-name/index.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "aliceblue": [240, 248, 255],
|   "antiquewhite": [250, 235, 215],
|   "aqua": [0, 255, 255],
```

If you are using webpack and haven't installed json-loader and set it up appropriately in webpack.config.js, then the webpack build will fail.

This is probably worth mentioning in your documentation somewhere given that most React devs use webpack, and plenty of people won't have json-loader installed and configured by default.

**Comment by felixakiragreen** [comment]
Okay, I'm on it

**Comment by felixakiragreen** [comment]
Does this still happen with 1.0? And does it happen in production or only development?
