### ISSUE TITLE
Disable click on date that is out of range

### ISSUE THREAD

**Issue by nicgordon** [dubert/react-kronos#14]
Is there a currently a way that we can stop users being able to click on dates that are out of range? Currently it still allows those values to be selected and the value of the field to be updated. It would be great if there were a prop we could pass to disable that functionality.

I'd be happy to create a PR, but coffeescript...

**Comment by felixakiragreen** [comment]
Yes, I actually already implemented this, I just have to release it. Expect release later today.

Also, as soon as I get the time, I'm going to do a rewrite in ES6.

**Comment by nicgordon** [comment]
Awesome! Love your work. If I have any time over the weekend I'll have a crack at ES6'ing the project

**Comment by beaucharman** [comment]
@dubert, you champion.

**Comment by felixakiragreen** [comment]
@nicgordon Added in 1.1!

@beaucharman Thanks man :) this is my first open source project so the encouragement means a lot
