### ISSUE TITLE
Allow all events to bubble up

### ISSUE THREAD

**Issue by nicgordon** [dubert/react-kronos#16]
There are currently some events that are being swallowed by the react-kronos library. If events like onBlur, onClick, onChange, etc. were able to bubble up (with their original event object argument), this would allow us to successfully use react-kronos with a library like redux-forms which relies on the availability of those events.

**Comment by felixakiragreen** [comment]
I'll take a look! Sorry for not seeing this early, I somehow didn't get a notification

**Comment by felixakiragreen** [comment]
@nicgordon Okay, I'm working on this now. Are there specific events that you want? Or do you just want all of them?

Please help me a bit, I'm not very familiar with exactly what you need / are looking for. Could you be a little more specific which events are getting swallowed? Or point to an example (like in redux-forms) that shows how all the events are bubbled up?

**Comment by oyeanuj** [comment]
@dubert With redux-forms, you are essentially exposing the `value`, `onBlur`, `onClick` and `onChange`so that the HOC in redux-form can tap into this and update redux. If you look at the examples in the redux-form repo, you'll see a bunch of examples which do the same.

Hope that helps :)

**Comment by felixakiragreen** [comment]
Should be addressed in 1.2.4!
