### ISSUE TITLE
Cannot import react-kronos

### ISSUE THREAD

**Issue by nicgordon** [dubert/react-kronos#17]
Just upgraded to 1.1.0 and we now get an error `Error: Cannot find module 'react-kronos'`.

It looks as though what is being published to npm needs to be a bit different, perhaps remove all of the dev stuff and define an entry point in your package.json

**Comment by bdart** [comment]
same here :+1:

**Comment by felixakiragreen** [comment]
I'll take a look! Sorry for not seeing this early, I somehow didn't get a notification

**Comment by felixakiragreen** [comment]
Should be fixed in 1.1.1 :)
