### ISSUE TITLE
Open datepicker on event/API

### ISSUE THREAD

**Issue by arnars** [dubert/react-kronos#19]
This is more of a suggestion for improvement than a real issue.

Have you thought of implementing an API to e.g. open the datepicker from a function, rather than onFocus?

That would be really useful (at least for me). My datepicker is currently hidden behind a button, and as it is now, I have no option to do more than just reveal the input field - as I see the documentation, I cannot open the datepicker programatically - is that correct?

Thanks for a great plugin - looking forward to 1.3 :dancers:

**Comment by felixakiragreen** [comment]
You're correct, there isn't a way to do that right now. But it would be a great addition.

I will add it to the next release. Any suggestions on how to do it?

**Comment by arnars** [comment]
I've only just briefly looked at your code, but perhaps an attribute like

```
openOn={this.method}
```

And when it is `true` it could trigger your toggle-method? Perhaps? :-)

**Comment by felixakiragreen** [comment]
I've been looking into this for the past few days, and I could only find two ways to do this. The first is to use refs to call a component method, and the second is to pass down a `visible` prop and `setVisibility` method to manage the visibility externally.

**Comment by felixakiragreen** [comment]
Added to 1.2. You can now do this with `this.refs.yourrefhere.refs.kronos.toggle()` and:

``` js
<Kronos
  ref='yourrefhere'
  date={this.state.datetime}
  onChange={this.onChange.bind(this)}
/>
```

For reference:
`toggle()` switches back and forth, `toggle(true)` only shows, `toggle(false)` only hides.
