### ISSUE TITLE
Reduce size (& dependencies)

### ISSUE THREAD

**Issue by felixakiragreen** [dubert/react-kronos#3]
Adding to a bundle.js increases the size by 30k + lines.

I think it's bundling React as well as every other dependency?

It also only does this with gulp+browserify, not webpack.

**Comment by felixakiragreen** [comment]
Make the dependencies more lax.

**Comment by luokuning** [comment]
Hi there, I install react-kronos via npm, and I found the `kronos.min.js` is about 390KB, and then I used browserify + uglifyjs to pack `index.js` without ReactJs included in, but after that I found the size of output was still nearly 227KB. How it to be so big? I think it is too heavyweight for browser use, Did I missed something or this is a normal case?

**Comment by felixakiragreen** [comment]
This is my first library so I'm still figuring a lot of things out. I'm pretty sure it has to do with the fact that it's pulling in React, Moment, Lodash, &c, even if they're already included in your project. I'll start working on this. Any ideas?

**Comment by luokuning** [comment]
Actually I'm not good at CommonJs way develop, so I'm afraid I can't give you some useful advice. But I packed `index.js` in 'dist' folder using `browserify index.js --ignore react | uglifyjs > kronos.min.js` command-line, so I guess the output js should not include `react.js`. 
According to my conjecture, one important reason for this result is that the build system will create a lot of redundant code to implement the conversion.
Besides, I think your first library is very good. Well done, mate,  I'll continue to focus on your project! :smile:

**Comment by felixakiragreen** [comment]
I've learned a bunch in the past month, and I'm planning to rewrite the library in ES6, and I now know how to address this problem!

**Comment by luokuning** [comment]
Great! I await the new version.

**Comment by felixakiragreen** [comment]
Updated to 1.0!
