### ISSUE TITLE
Define Locale Override, Momentjs

### ISSUE THREAD

**Issue by arnars** [dubert/react-kronos#30]
Hi (again),

On the pages where I am using react-kronos, I get the following warning from Momentjs:
http://momentjs.com/guides/#/warnings/define-locale/

I'm using 1.2.3 of react-kronos and 2.13.0 of Momentjs

I assume this is something related to react-kronos' use of Momentjs? Perhaps you can confirm.

All the best,
Anders

**Comment by felixakiragreen** [comment]
Should be fixed in 1.2.4!
