### ISSUE TITLE
Support React v15

### ISSUE THREAD

**Issue by belkosyak** [dubert/react-kronos#31]
Please add support for React v15, it has been released enough time ago to start using it :)

**Comment by belkosyak** [comment]
Please take a look at #27. I updated this PR to start using React v15, tested quite well, everything works :) . Also fixed bug on demo page.

**Comment by felixakiragreen** [comment]
@belkosyak Thanks! I will try to get this released by the weekend

**Comment by belkosyak** [comment]
Really looking forward, thanks in advance!

**Comment by felixakiragreen** [comment]
Should be fixed in 1.2.4!
