### ISSUE TITLE
Uncaught TypeError: Cannot read property 'format' of null (+1)

### ISSUE THREAD

**Issue by arnars** [dubert/react-kronos#32]
Hi, it's me again. Sorry for all these issues, but we're really just enjoying using react-kronos, and the sometimes things pops up!
1. Open http://dubert.github.io/react-kronos/ 
2. Place the cursor in the first input date field
3. Hit backspace until no more content is in the field
4. Hit enter
5. Watch the console - the above error should pop up.
#### +1

Also - in our solution (not on your site) I get an error extra between 4 and 5. When the input field is empty I get this:

```
Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.
```

I can't seem to find out which event (if any?) the Kronos triggers when deleting content via backspace. These errors could be related, so my guess is that if you fix the first, mine will be fixed as well.

Again - thanks for your always swift replies and fixes! :-)

**Comment by arnars** [comment]
This could be related to the last issue: https://github.com/facebook/react/pull/5048 - it's a part of the changelog at https://facebook.github.io/react/blog/

**Comment by felixakiragreen** [comment]
Hey @arnars ! Thanks for reporting this issue. 

Should be fixed in 1.2.5 - let me know if you encounter any more issues!

**Comment by arnars** [comment]
Dear @dubert,

You rock!
I have no issues now, thanks to your update. It's a real pleasure using a plugin that is so consistently maintained. Thank you.

**Comment by felixakiragreen** [comment]
Thank you! It's always nice to hear positive feedback from people using my component.
