### ISSUE TITLE
UI goes crazy when clearing out the field and start typing

### ISSUE THREAD

**Issue by hugotox** [dubert/react-kronos#33]
Hi!

Thanks for this component. See from your demo page, the controlled example goes bad when you clear out the field and type any number

![screen shot 2016-06-07 at 8 03 52 pm](https://cloud.githubusercontent.com/assets/1758062/15878666/36e55b12-2cf3-11e6-9fa5-4e0f924f1ff5.jpeg)

**Comment by felixakiragreen** [comment]
Thanks for catching this and reporting it! Fixed in 1.2.6
