### ISSUE TITLE
Controlled visibility bug when navigating in months

### ISSUE THREAD

**Issue by arnars** [dubert/react-kronos#34]
Hi again,

I'm using the controlled version of http://dubert.github.io/react-kronos/

When clicking on the `<<` or `>>` the date picker closes. This seems to be an error, as it disrupts the UI-experience. If `controlVisibility={false}` the problem goes away.

All the best,
Anders

**Comment by felixakiragreen** [comment]
Thanks for catching this and reporting it! Fixed in 1.2.7
