### ISSUE TITLE
[Suggestion] Min/max for time picker

### ISSUE THREAD

**Issue by yury-dymov** [dubert/react-kronos#37]
Hello again!

I am using kronos only as time picker. It would be nice if min and max props could be used for this use case as well. I.e. possible restaurant delivery time is between 10 AM and 9 PM.

Kind regards,
Yuri.

**Comment by felixakiragreen** [comment]
Excellent suggestion. I will implement this for the time picker as well!

**Comment by felixakiragreen** [comment]
Added the `minTime` and `maxTime` props in 1.3.0, so you if you set them, it will only apply to the time picker.

**Comment by yury-dymov** [comment]
Thank you! :)
