### ISSUE TITLE
visibility issue with visibility controlled

### ISSUE THREAD

**Issue by amelon** [dubert/react-kronos#41]
I'm trying to control visibility and have some issues.

You can reproduce issues at http://dubert.github.io/react-kronos/ on Controlled part.

First issue:
you click on "Toggle Visibility" and then click "next" or "previous" month (on nav bar) => calendar disapear (it should remain visible)

Second issue:
you click on "Toggle Visibility" and then focus input and then "Toggle Visibility" => calendar blink but remains visible (it should disapear)

Thanks for your work :)

**Comment by felixakiragreen** [comment]
Confirming I see this. Thanks for catching it. I'm pretty busy atm, but I'll try to get a fix out within the next week.

**Comment by felixakiragreen** [comment]
Should be fixed in 1.4.2
