### ISSUE TITLE
`id` prop should be on `input` and not on `Calendar`

### ISSUE THREAD

**Issue by KCraw** [dubert/react-kronos#43]
For of all, thanks for this library! Totally agree with your reasoning for creating it, and we're using it it in our app. Happy to help out with PRs as they come up. 

In `index.js`, I think we should really be using `props.id` on the `input` and not on `Calendar`. This way we can use  `<label>` with `htmlFor=` instead of wrapping `<Kronos>` in a label, which causes problems -- it ends up also being a label for the calendar, so selecting a date/time triggers a focus event and the calendar can never close. 

Is there a reason for having an `id` prop for the Calendar that I'm missing? If so, maybe have `props.id` and `props.calendarId`?

**Comment by felixakiragreen** [comment]
Thank you for reporting! The `props.id` on Calendar is for when there are multiple instances of Kronos, they can be distinguished from each other (for styling purposes).

I think we could definitely do `props.id` on the input and `props.calendarId` on the calendar. I can take a stab at it as soon as I have the time (no promises, but hopefully within a week or two), but if it's more urgent, I gladly welcome PRs!

**Comment by felixakiragreen** [comment]
_Just released **1.6.0**!_

Try out the `inputId` prop, it will pass the string through to the input.
