### ISSUE TITLE
Changing the time step

### ISSUE THREAD

**Issue by flyalex** [dubert/react-kronos#48]
Hi!

Thank you for your job!

How can I change time step in time picker for 5 mins?

**Comment by felixakiragreen** [comment]
It's not possible yet, but I have plans to add a property that can configure this.

**Comment by ovarr** [comment]
@dubert any schedule on this? PR #49 has been waiting for a while.

**Comment by felixakiragreen** [comment]
Hi @ovarr - I will try to get in this weekend! I've been quite overwhelmed at work, and haven't had the time to work on this.

**Comment by felixakiragreen** [comment]
_Just released **1.6.0**!_

Try out the `timeStep` prop.
