### ISSUE TITLE
disable component

### ISSUE THREAD

**Issue by amelon** [dubert/react-kronos#50]
hello,

can't find any option to disable component.

Could be fine to have a `disabled` prop as we do for an `input` element (`<input disabled/>`).

````
...
render() {
   return <Kronos disabled />
}
...
````

Or do you have other suggestion?

**Comment by marktkimball** [comment]
Would like this option as well.

**Comment by felixakiragreen** [comment]
What would you like the behavior to be when it is disabled? Hidden? Visible but not interactive (greyed out)?

**Comment by marktkimball** [comment]
@dubert I think greyed out with the `cursor: not-allowed;` css when hovering the element would make sense.

**Comment by yrokhlin** [comment]
Greyed out like typical disabled input behavior, need this as well.

**Comment by schuchowsky** [comment]
Hey guys, while we don't have this feature, I solved it with this workaround: https://stackoverflow.com/questions/28083708/how-to-disable-clicking-inside-div

Just use the css pointer-events:none; in a parent element.

**Comment by felixakiragreen** [comment]
_Just released **1.6.0**!_

Try out the `disabled` prop.
