### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by anvk** [dubert/react-kronos#52]
It would be great to have properties which will allow to set custom styling on this component. Right now I have to write custom LESS files to overwrite default looks. Put `style` and `className` properties would be amazing. I assume there would be different properties to style: input, time dropdown, calendar.

Thank you !

**Comment by Nantris** [comment]
`className` would be great!

**Comment by felixakiragreen** [comment]
_Just released **1.6.0**!_

Try out the `inputStyle`, `inputClassName`, `calendarStyle`, and `calendarClassName` props!
