### ISSUE TITLE
Remove PropTypes for React 16 Compatibility?

### ISSUE THREAD

**Issue by Nantris** [dubert/react-kronos#60]
Is there a plan to do this? Thank you very much for the great package.

**Comment by felixakiragreen** [comment]
It should already be done in `1.6`. Can you show the warning/error you are receiving? And what version are you on?

**Comment by Nantris** [comment]
@dubert thanks for the reply. I thought I was fully up to date, but I'll double check and report back.

**Comment by Nantris** [comment]
Just looking at the code in the `src` directories, I can see that `Static PropTypes` is still in use.


**https://github.com/dubert/react-kronos/blob/master/src/calendar.js**:

```
 static propTypes = {
    datetime: PropTypes.object.isRequired,
    onSelect: PropTypes.func.isRequired,
    level: PropTypes.string.isRequired,
    setLevel: PropTypes.func.isRequired,
    onMouseDown: PropTypes.func,
    onMouseUp: PropTypes.func,
  }
```

**Comment by felixakiragreen** [comment]
Updated to 1.7.0 with React 16. Should be fixed.
