### ISSUE TITLE
React 16 error

### ISSUE THREAD

**Issue by tnguven** [dubert/react-kronos#64]
I am getting an error like this after migrate to React 16.

`Error: Minified React error #149; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=149&args[]=kronos for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

**Comment by felixakiragreen** [comment]
Thanks for reporting. I will update the package to React 16 soon™.

**Comment by paramaggarwal** [comment]
```
warning "react-kronos@1.6.0" has incorrect peer dependency "react@^15.6.1".
warning "react-kronos@1.6.0" has incorrect peer dependency "react-dom@^15.6.1".
```

Thanks for the package, here is the related warning as well.

**Comment by felixakiragreen** [comment]
Updated to 1.7.0 with React 16. Should be fixed.
