### ISSUE TITLE
moment.locale is not a function (moment-range 1.1.0 incompatibility)

### ISSUE THREAD

**Issue by santihbc** [dubert/react-kronos#7]
Doing a clean npm install to my project, I constantly get this error. It's located in styles.js in the "initializeMoment" method.

Please give me a solution to this @dubert , it's blocking the deployment of my app. Thanks

**Comment by santihbc** [comment]
I know what the problem is. If you include moment-range 1.1.0 (new version released yesterday) then react-kronos uses that dependency which breaks the current build of your repo @dubert .

**Comment by felixakiragreen** [comment]
Thanks for catching this. I will fix this and release a new version asap.

**Comment by felixakiragreen** [comment]
Looked into it, it's definitely a problem with moment-range. Filled an issue [here](https://github.com/gf3/moment-range/issues/77) and I'll release a workaround in the mean time.

**Comment by felixakiragreen** [comment]
Fixed with 0.2.0 (and moment-range 1.2.0)
