### ISSUE TITLE
Incompatibility with React 16.3.0 and up

### ISSUE THREAD

**Issue by mikebcbc** [dubert/react-kronos#75]
`Invariant Violation: Element ref was specified as a string (kronos) but no owner was set.`

When react-dom and react are past version 16.2.0, this package breaks. I believe this error is in reference to line 49 of `src/styled-component.js`. According [the documentation](https://reactjs.org/warnings/refs-must-have-owner.html), you can not use refs on function components. In version 16.3.0, a couple of new APIs handling this were introduced so I believe the error was just suppressed until then. 

I imagine it's pretty simple to fix this and update the package - until then, `react-kronos` doesn't work with any version of `react` or `react-dom` past 16.2.0.

**Comment by felixakiragreen** [comment]
Thanks for bringing this up. I will try to get it updated soon. Been pretty busy working on other projects lately.

**Comment by mikebcbc** [comment]
@xenophilicibex Hey there! I just wanted to check in and see if this is still being updated?

**Comment by felixakiragreen** [comment]
My apologies @mikebcbc . I will try to get to it this week, but I would also welcome a PR to update it!

**Comment by felixakiragreen** [comment]
Updated!
