### ISSUE TITLE
npm install error with package "jss"

### ISSUE THREAD

**Issue by santihbc** [dubert/react-kronos#8]
![image](https://cloud.githubusercontent.com/assets/2404757/8889816/c95cec58-32e9-11e5-9c48-37304a0fa912.png)

**Comment by santihbc** [comment]
@dubert any news on this?

**Comment by felixakiragreen** [comment]
@santihbc hey, I was out yesterday, looking into it now. Seems like a problem with JSS. I'll post an update.

**Comment by felixakiragreen** [comment]
@santihbc fixed in 0.2.2

I'm planning a rewrite in ES6, which should significantly slim down the package, and add some new features :)
