### ISSUE TITLE
error in date

### ISSUE THREAD

**Issue by vishgirase95** [dubert/react-kronos#80]
input-
import React from "react"
import ReactDOM from "react-dom"

let c = new date();

ReactDOM.render(
    
    <h1>Hello sir, good morning, {c}</h1>,
    document.getElementById('root')
);
output error-
 'date' is not defined  no-undef

**Comment by felixakiragreen** [comment]
@vishgirase95 try `let c = new Date();` (capital `D`, not lowecase `d`)
